apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/hello-world:98d0023c5556973b1cd722bc0d29246f5970cc47
        name: demo-app
        ports: 
        - containerPort: 8080
