apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/hello-world:fd43d0850a551f0ca83502ab8bfacccb98b864be
        name: demo-app
        ports: 
        - containerPort: 8080
