apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/hello-world:73fcdf7dc7df00d8a5b81446961b39d3bf28ee58
        name: demo-app
        ports: 
        - containerPort: 8080
