apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/hello-world:5c07169cd8cc92572113eff91d007adfb3850c86
        name: demo-app
        ports: 
        - containerPort: 8080
