apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/demo-app:2fb62ba91bcabed6963b1704e18a255673829289
        name: demo-app
        ports: 
        - containerPort: 8080
