apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/demo-app:50a1ec47013d37c88c7e94d15b63be3e6227943c
        name: demo-app
        ports: 
        - containerPort: 8080
