apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/demo-app:5923d9af12cfb39bd7c81cd8d0d88efd4cec372f
        name: demo-app
        ports: 
        - containerPort: 8080
