apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/demo-app:cdee8c88fd345a5d96ce25f85530bd38e7140913
        name: demo-app
        ports: 
        - containerPort: 8080
