apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template: 
    metadata: 
      labels: 
        app: demo-app
    spec: 
      containers: 
      - image: dhruvbhartia07/demo-app:08ea81efd8ca60982bafa3767e11ae57e7359981
        name: demo-app
        ports: 
        - containerPort: 8080
